name: Build Android APK & SO

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK and CMake
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" "ndk;25.2.9519653"

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: eink256-build
        path: '**/*.apk'
